service: copaco-azure-test-function

frameworkVersion: '3'

provider:
  name: azure
  region: West Europe
  runtime: python3.8

plugins:
  - serverless-azure-functions
  - serverless-offline

package:
  patterns:
    - '!env/**'
    - '!.env/**'
    - '!local.settings.json'
    - '!.vscode/**'
    - '!__pycache__/**'
    - '!node_modules/**'
    - '!.python_packages/**'
    - '!.funcignore'
    - '!package.json'
    - '!package-lock.json'
    - '!.gitignore'
    - '!.git/**'

functions:
  random:
    handler: src/handlers/random.main
    events:
      - http:
          path: /random
          method: GET
          authLevel: function

  search:
    handler: src/handlers/search.main
    events:
      - http:
          path: /search
          method: GET
          authLevel: function
